### ISSUE TITLE
Chọn đề tài

### ISSUE THREAD

**Issue by vuxuanvn** [vuxuanvn/SE03-Group17#2]
Thảo luận về đề tài của phần bài tập cuối kì

**Comment by dangvantu99CM** [comment]
Đề xuất : Hệ thống quản lý đặt hàng trung quốc

**Comment by vuxuanvn** [comment]
Nền web hay desktop hay mobile

**Comment by dangvantu99CM** [comment]
Chạy trên nền web là chính

**Comment by vuxuanvn** [comment]
ok

**Comment by vuxuanvn** [comment]
vậy là web quản lí bán hàng TQ nhé

**Comment by dangvantu99CM** [comment]
ok
